[package]
name = "model"
version = "0.1.0"
authors = ["Gnosis Developers <developers@gnosis.io>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = "1"
bigdecimal = "0.2"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
derivative = "2.2"
ethabi = "15.0"
enum-utils = "0.1"
hex = { version = "0.4", default-features = false }
hex-literal = "0.3"
lazy_static = "1.4"
maplit = "1.0"
num = "0.4"
num-bigint = "0.3"
primitive-types = { version = "0.10" }
secp256k1 = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "1.11", default-features = false, features = ["macros"] }
web3 = { git = "https://github.com/tomusdrw/rust-web3.git", rev="a425fa747bca69c7aede4d2c2828f7267d79227e", default-features = false, features = ["signing"] }

[dev-dependencies]
serde_json = "1.0"
