pull_request_rules:
  - name: Merge approved and green PRs with `merge when green` label
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=rust
      - check-success=openapi
      - base=main
      - label=merge when green
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        commit_message: title+body
