branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

os: linux
dist: focal

jobs:
  fast_finish: true
  include:
    - name: "Test Rust"
      language: rust
      rust: stable
      env:
        - SCCACHE_VERSION=0.2.13
        - SCCACHE=$HOME/.sccache/bin/sccache
        - RUSTC_WRAPPER=$SCCACHE
        - CARGO_INCREMENTAL=0
      cache:
        directories:
          - $HOME/.cache/sccache
          - $HOME/.cargo
          - $HOME/.rustup
      before_install:
        - rustup component add clippy rustfmt
        - cargo clippy --version
        - cargo fmt --version
        - |
          mkdir -p $HOME/.sccache/bin
          pushd $HOME/.sccache
          curl -LO https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz
          tar -C bin -xvf sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz --wildcards '*/sccache' --strip 1
          popd
        - $SCCACHE --version
      before_script:
        # For e2e tests
        - GANACHE_DOCKER_CONTAINER=$(docker run -d trufflesuite/ganache-cli)
        - (cd contracts; cargo run --bin deploy --features bin)
      script:
        - cargo fmt -- --check
        - cargo clippy --locked --workspace --all-features --all-targets -- -D warnings
        - cargo test --workspace --all-features
      after_script:
        - docker logs $GANACHE_DOCKER_CONTAINER
        - docker rm -f $GANACHE_DOCKER_CONTAINER
      before_cache:
        - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
      deploy:
        - provider: script
          script: ./docker/deploy.sh $TRAVIS_BRANCH
          on:
            branch: main
        - provider: script
          script: ./docker/deploy.sh $TRAVIS_TAG
          on:
            tags: true
    - name: "Validate Openapi"
      language: generic
      before_install:
        - npm install -g @apidevtools/swagger-cli
      script:
        - swagger-cli validate orderbook/openapi.yml
