branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

os: linux
dist: focal

jobs:
  include:
    - name: "Deploy"
      language: minimal
      deploy:
        - provider: script
          script: ./docker/deploy.sh $TRAVIS_BRANCH
          on:
            branch: main
        - provider: script
          script: ./docker/deploy.sh $TRAVIS_TAG
          on:
            tags: true
