[workspace]
members = [
    "contracts",
    "e2e",
    "model",
    "orderbook",
    "shared",
    "solver",
]

default-members = [
    "contracts",
    "model",
    "orderbook",
    "shared",
    "solver",
]
