[workspace]
members = [
    "contracts",
    "e2e",
    "model",
    "orderbook",
    "shared-arguments",
    "solver",
    "tracing-setup",
]

default-members = [
    "contracts",
    "model",
    "orderbook",
    "shared-arguments",
    "solver",
    "tracing-setup",
]
