openapi: 3.0.3
info:
  version: 0.0.1
  title: Order Book API
servers:
- url: http://localhost:8080
  description: Local
paths:
  /api/v1/orders:
    post:
      summary: Create a new order.
      responses:
        201:
          description: Order has been accepted.
      requestBody:
        description: The order to create.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderNew"
  /api/v1/orders:
    get:
      summary: Get existing orders.
      # TODO: Later we could add filters through the url query to only get orders matching specific tokens etc.
      responses:
        200:
          description: existing orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderFull"
components:
  schemas:
    Address:
      description: Ethereum 40 byte address encoded as a hex without `0x` prefix.
      type: string
      example: "6810e776880c02933d47db1b9fc05908e5386b96"
    TokenAmount:
      description: Amount of a token. uint256 encoded in decimal.
      type: string
      example: "1234567890"
    OrderNew:
      description: Data a user provides when creating a new order.
      type: object
      properties:
        sellToken:
          $ref: "#/components/schemas/Address"
        buyToken:
          $ref: "#/components/schemas/Address"
        sellAmount:
          $ref: "#/components/schemas/TokenAmount"
        buyAmount:
          $ref: "#/components/schemas/TokenAmount"
        validTo:
          description: Time offset in seconds from epoch until which the order is valid. uint32.
          type: integer
        appData:
          description: Arbitrary identifier sent along with the order. Could be used to track the interface or other meta-aspects of the order. uint32.
          type: integer
        feeAmount:
          $ref: "#/components/schemas/TokenAmount"
        orderKind:
          description: Is this a buy order or sell order?
          type: string
          enum: [buy, sell]
        partiallyFillable:
          description: Is this a fill-or-kill order or a partially fillable order?
          type: boolean
        signature:
          description: 65 bytes encoded as hex without `0x` prefix. v + r + s from the spec.
          example: "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    OrderExtra:
      description: Extra order data that is returned to users when querying orders but not provided by users when creating orders.
      type: object
      properties:
        creationTime:
          description: Creation time of the order. Encoded as ISO 8601 UTC.
          type: string
          example: "2020-10-22T07:57:18Z"
        owner:
          $ref: "#/components/schemas/Address"
    OrderFull:
      allOf:
        - $ref: "#/components/schemas/OrderNew"
        - $ref: "#/components/schemas/OrderExtra"
