[package]
name = "contracts"
version = "0.1.0"
authors = ["Gnosis Developers <developers@gnosis.io>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[[bin]]
name = "vendor"
required-features = ["bin"]

[features]
default = []
bin = [
    "anyhow",
    "env_logger",
    "ethcontract-generate",
    "log",
    "serde_json",
]

[dependencies]
ethcontract = { git = "https://github.com/gnosis/ethcontract-rs.git", branch = "eip1559", default-features = false }
serde = "1.0"

# [bin-dependencies]
anyhow = { version = "1.0", optional = true }
env_logger = { version = "0.9", optional = true }
ethcontract-generate = { git = "https://github.com/gnosis/ethcontract-rs.git", branch = "eip1559", optional = true }
log = { version = "0.4", optional = true }
serde_json = { version = "1.0", optional = true }

[build-dependencies]
ethcontract = { git = "https://github.com/gnosis/ethcontract-rs.git", branch = "eip1559", default-features = false }
ethcontract-generate = { git = "https://github.com/gnosis/ethcontract-rs.git", branch = "eip1559" }
maplit = "1.0"
