[package]
name = "e2e"
version = "1.0.0"
authors = ["Gnosis Developers <developers@gnosis.io>"]
edition = "2018"

[dev-dependencies]
contracts = { path = "../contracts" }
ethcontract = { version = "0.11",  default-features = false, features = ["http"] }
hex-literal = "0.3"
model = { path = "../model" }
orderbook = { path = "../orderbook" }
reqwest = "0.10"
secp256k1 = "0.20"
serde_json = "1.0"
shared = { path = "../shared" }
solver = { path = "../solver" }
tokio = { version = "0.2", features = ["macros"] }
web3 = { version = "0.15", default-features = false }
