[package]
name = "shared"
version = "0.1.0"
authors = ["Gnosis Developers <developers@gnosis.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
assert_approx_eq = "1.1"
async-trait = "0.1"
atty = "0.2"
contracts = { path = "../contracts" }
derivative = "2.2"
ethcontract = { git = "https://github.com/gnosis/ethcontract-rs.git", rev = "34c618cf63ad4750d1d9198eada85f3d1cf334ab", default-features = false }
ethcontract-mock = { git = "https://github.com/gnosis/ethcontract-rs.git", rev = "34c618cf63ad4750d1d9198eada85f3d1cf334ab" }
futures = "0.3"
gas-estimation = { git = "https://github.com/gnosis/gp-gas-estimation.git", tag = "v0.3.4", features = ["web3_", "tokio_"] }
hex = { version = "0.4", default-features = false }
hex-literal = "0.3"
http = "0.2.5"
itertools = "0.10"
lazy_static = "1.4.0"
lru = "0.7"
maplit = "1.0"
mockall = "0.10"
model = { path = "../model" }
num = "0.4"
num-bigint = "0.3"
once_cell = "1.8.0"
primitive-types = "0.9"
prometheus = "0.13"
prometheus-metric-storage = "0.4"
reqwest = { version = "0.11", features = ["json"] }
scopeguard = "1.1.0"
serde = "1.0"
serde_json = "1.0"
serde_with = { version = "1.10", default-features = false }
structopt = { version = "0.3", default-features = false }
thiserror = "1.0"
tokio = { version = "1.12", features = ["macros", "time"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt"] }
url = "2.2"
warp = "0.3"
web3 = { git = "https://github.com/tomusdrw/rust-web3.git", rev="2e2d1dfa906aa2dff6312b97d0d5ba804e9c8c6e", default-features = false }

[dev-dependencies]
regex = "1.5.4"
