[package]
name = "shared"
version = "0.1.0"
edition = "2018"

[dependencies]
atty = "0.2"
structopt = { version = "0.3", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.2"
url = "2.2"
