[package]
name = "testlib"
version = "0.1.0"
authors = ["Gnosis Developers <developers@gnosis.io>"]
edition = "2018"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contracts = { path = "../contracts" }
ethcontract = { version = "0.16.0", default-features = false }
ethcontract-mock = { version = "0.16.0" }
hex-literal = "0.3"
