[package]
name = "orderbook"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
hex = { version = "0.4", default-features = false }
model = { path = "../model" }
primitive-types = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared-arguments = { path = "../shared-arguments" }
structopt = { version = "0.3" }
tokio = { version = "0.2", features =[ "macros", "time"] }
tracing = "0.1"
tracing-setup = { path = "../tracing-setup" }
warp = "0.2"
