[package]
name = "orderbook"
version = "0.1.0"
edition = "2018"

[lib]
name = "orderbook"
path = "src/lib.rs"

[[bin]]
name = "orderbook"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
contracts = { path = "../contracts" }
ethcontract = { version = "0.9", default-features = false }
futures = "0.3.9"
hex = { version = "0.4", default-features = false }
model = { path = "../model" }
primitive-types = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared-arguments = { path = "../shared-arguments" }
structopt = { version = "0.3" }
tokio = { version = "0.2", features =[ "macros", "time"] }
tracing = "0.1"
tracing-setup = { path = "../tracing-setup" }
warp = "0.2"
web3 = { version = "0.13", default-features = false, features = ["http-tls"] }

[dev-dependencies]
hex-literal = "0.3"
secp256k1 = "0.17"
