[package]
name = "shared"
version = "0.1.0"
authors = ["Gnosis Developers <developers@gnosis.io>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
assert_approx_eq = "1.1"
async-trait = "0.1"
atty = "0.2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
contracts = { path = "../contracts" }
derivative = "2.2"
ethcontract = { git = "https://github.com/gnosis/ethcontract-rs.git", rev = "cafcac443f37cfe1e0e18b03a987a30b61b54695", default-features = false }
ethcontract-mock = { git = "https://github.com/gnosis/ethcontract-rs.git", rev = "cafcac443f37cfe1e0e18b03a987a30b61b54695" }
futures = "0.3"
gas-estimation = { git = "https://github.com/gnosis/gp-gas-estimation.git", tag = "v0.4.0", features = ["web3_", "tokio_"] }
hex = { version = "0.4", default-features = false }
hex-literal = "0.3"
http = "0.2.4"
itertools = "0.10"
lazy_static = "1.4.0"
lru = "0.7"
maplit = "1.0"
mockall = "0.10"
model = { path = "../model" }
num = "0.4"
num-bigint = "0.3"
once_cell = "1.8.0"
primitive-types = "0.10"
prometheus = "0.13"
prometheus-metric-storage = "0.4"
reqwest = { version = "0.11", features = ["json"] }
scopeguard = "1.1.0"
serde = "1.0"
serde_json = "1.0"
serde_with = { version = "1.11", default-features = false }
structopt = { version = "0.3", default-features = false }
thiserror = "1.0"
time = { version = "0.3", features = ["macros"] }
tokio = { version = "1.14", features = ["macros", "time"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "time"] }
url = "2.2"
warp = { version = "0.3", default-features = false }
web3 = { git = "https://github.com/tomusdrw/rust-web3.git", rev="a425fa747bca69c7aede4d2c2828f7267d79227e", default-features = false }

[dev-dependencies]
regex = "1.5.4"
