name: pull request
on:
  pull_request:
  # We require PRs to be up to date before merging so technically it is not needed run the rust job
  # on main. However for the cache to be usable in PRs we do need the job on main.
  push:
    branches: [main]
jobs:
  rust-misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          rustup --version
          rustup show
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --workspace --all-features --all-targets -- -D warnings
  rust-tests:
    runs-on: ubuntu-latest
    env:
      # Shrink artifact size by not including debug info. Makes build faster and shrinks cache.
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      FLYWAY_VERSION: 7.3.1
      # Flyway is connecting via TCP/IP (authentication via password), whereas psql connects via Unix-domain sockets (authentication via username)
      # We set the db password of $USER to this value which is also used by the flyway command
      FLYWAY_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Cache flyway
        uses: actions/cache@v2
        with:
          path: flyway-${{ env.FLYWAY_VERSION }}
          key: ${{ runner.os }}-build-flyway-${{ env.FLYWAY_VERSION }}
      - run: "[[ -d flyway-${FLYWAY_VERSION} ]] || (curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.tar.gz -o flyway-commandline-${FLYWAY_VERSION}.tar.gz && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz)"
      - run: |
          npm install hardhat
          cat > hardhat.config.js <<EOF
          module.exports = {
            networks: {
              hardhat: {
                initialBaseFeePerGas: 0,
                accounts: {
                  accountsBalance: "1000000000000000000000000"
                },
              },
            },
          };
          EOF
          node_modules/.bin/hardhat node &
      - run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser $USER
          sudo -u postgres createdb $USER
          psql -c "ALTER USER $USER PASSWORD '$FLYWAY_PASSWORD';"
          flyway-${FLYWAY_VERSION}/flyway -url="jdbc:postgresql:///" -user=$USER -locations="filesystem:database/sql/" migrate
      # Running deploy causes rebuild because contracts crate changes so we do it before building
      # the rest.
      - run: cargo build --features bin --bin deploy
      - run: cargo run --features bin --bin deploy
      - run: cargo test --no-run
      - run: cargo test
      # tests requiring a Postgres instance.
      - run: cargo test postgres -- --ignored --test-threads 1
      # tests requiring a local ethereum node
      - run: cargo test local_node -- --ignored --test-threads 1
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @apidevtools/swagger-cli
      - run: node_modules/.bin/swagger-cli validate orderbook/openapi.yml
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup toolchain install nightly --component llvm-tools-preview
      - name: Install cargo-llvm-cov
        run: curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
