name: pull request
on:
  pull_request:
  # We require PRs to be up to date before merging so technically it is not needed run the rust job
  # on main. However for the cache to be usable in PRs we do need the job on main.
  push:
    branches: [main]
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          npm install ganache-cli
          node_modules/.bin/ganache-cli --networkId 5777 --gasLimit 10000000 --gasPrice 0&
      - run: |
          rustup --version
          rustup show
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt --all -- --check
      - run: cargo run --bin deploy --features bin
        working-directory: contracts
      - run: cargo clippy --locked --workspace --all-features --all-targets -- -D warnings
      - run: cargo test --locked --workspace --all-features
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @apidevtools/swagger-cli
      - run: node_modules/.bin/swagger-cli validate orderbook/openapi.yml
