name: pull request
on:
  pull_request:
  # We require PRs to be up to date before merging so technically it is not needed run the rust job
  # on main. However for the cache to be usable in PRs we do need the job on main.
  push:
    branches: [main]
jobs:
  rust-misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          rustup --version
          rustup show
          cargo --version
          cargo fmt --version
          cargo clippy --version
      - run: cargo fmt --all -- --check
      - run: cargo clippy --locked --workspace --all-features --all-targets -- -D warnings
  rust-tests:
    runs-on: ubuntu-latest
    env:
      # Shrink artifact size by not including debug info. Makes build faster and shrinks cache.
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      FLYWAY_VERSION: 7.3.1
      # Flyway is connecting via TCP/IP (authentication via password), whereas psql connects via Unix-domain sockets (authentication via username)
      # We set the db password of $USER to this value which is also used by the flyway command
      FLYWAY_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Cache flyway
        uses: actions/cache@v2
        with:
          path: flyway-${{ env.FLYWAY_VERSION }}
          key: ${{ runner.os }}-build-flyway-${{ env.FLYWAY_VERSION }}
      - run: "[[ -d flyway-${FLYWAY_VERSION} ]] || (curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}.tar.gz -o flyway-commandline-${FLYWAY_VERSION}.tar.gz && tar -xzf flyway-commandline-${FLYWAY_VERSION}.tar.gz && rm flyway-commandline-${FLYWAY_VERSION}.tar.gz)"
      - run: cargo test --locked --all-features
      - run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createuser $USER
          sudo -u postgres createdb $USER
          psql -c "ALTER USER $USER PASSWORD '$FLYWAY_PASSWORD';"
          flyway-${FLYWAY_VERSION}/flyway -url="jdbc:postgresql:///" -user=$USER -locations="filesystem:database/sql/" migrate 
          # Postgres tests should not run in parallel because they use the same database.
          cargo test --locked --workspace --all-features --jobs 1 postgres -- --ignored --test-threads 1
      - run: |
          npm install ganache-cli
          node_modules/.bin/ganache-cli --networkId 5777 --gasLimit 10000000 --gasPrice 0  --defaultBalanceEther 1000000 &
      - run: cargo run --bin deploy --features bin
        working-directory: contracts
      - run: cargo test --locked --package e2e
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @apidevtools/swagger-cli
      - run: node_modules/.bin/swagger-cli validate orderbook/openapi.yml
